### ISSUE TITLE
New Window instead of Lightbox

### ISSUE THREAD

**Issue by jade7669** [OOlashyn/PCF-AttachmentGalleryControl#12]
Hi there,

I was wondering if it is possible to set the enlarged image on a separated window (not downloaded) instead of lightbox like what you currently have.  Please advise!!

**Comment by OOlashyn** [comment]
Hi @jade7669,
There is no functionality like that in my current project. However, you can extend the code and try to implement something like [this](https://stackoverflow.com/questions/46666559/base64-image-open-in-new-tab-window-is-not-allowed-to-navigate-top-frame-naviga) - basically opening base64 image in a new tab by generating a new HTML page with image page to open.
