### ISSUE TITLE
control not loading MP4 file in chrome

### ISSUE THREAD

**Issue by sandeepcse23** [OOlashyn/PCF-AttachmentGalleryControl#2]
Hi,
using this control on D365 CE. Loading MP4 file on chrome loads black page with screen player with play button and other buttons but does not play the file. This works in IE and Edge. Any thoughts?

**Comment by OOlashyn** [comment]
Hi @sandeepcse23,
Sorry for not replying earlier. My control supports only images and pdf files by default. I will investigate this and will get back to you soon.

**Comment by OOlashyn** [comment]
Hi @sandeepcse23,
I am right now working on the new release of my component and I will include support for MP4 in it. It will be ready in upcoming week or so.
