### ISSUE TITLE
PCF Stop Working

### ISSUE THREAD

**Issue by TBOCRM** [OOlashyn/PCF-AttachmentGalleryControl#36]
Hi,

First of all, thank you for this great work.

Second, I have a problem on two different accounts that use your PCF: PDFs are no longer displayed. I tried loading different documents and on two different "tenants".

Can you test it on your side? Any idea where this could come from?

Again thank for your work ! 
Hopping for a reply, have a nice day,

Tristan

**Comment by OOlashyn** [comment]
Hi, Tristan (@TBOCRM),
I will check this out on the weekends. Meanwhile, can you open the console and check if you see any errors associated with my control? And if you see them share them with me. It will make investigation much easier.

**Comment by TBOCRM** [comment]
Hi OOlashyn,
Thanks for your quick answer, it's seams like a package issue : 
![image](https://github.com/OOlashyn/PCF-AttachmentGalleryControl/assets/150790047/994cee6f-9208-4386-9802-673aebf7da6f) 
?

**Comment by OOlashyn** [comment]
Hi @TBOCRM ,
Yes, apparently the latest version of pdf.js doesn't use js anymore and they switched to modules in the build output (so mjs). That's why my current import is no longer valid. I will be working on the fix to update control this week and will release a hotfix probably somewhere next week or sooner.

**Comment by OOlashyn** [comment]
Hi @TBOCRM,

I fixed the issue and created a new release version. Unfortunately, as this control was created before PCF was Generally Available I wasn't able to just update the solution. Instead, I needed to recreate it with a new tooling which made it incompatible with the old version. Please delete the old solution and install the new one.

**Comment by TBOCRM** [comment]
Hi @OOlashyn,

Ok thank again for your quick action. I will do that. 

Have a nice day.
