### ISSUE TITLE
Please advise how I set the preview up :)

### ISSUE THREAD

**Issue by stella12131213** [OOlashyn/PCF-AttachmentGalleryControl#6]
Hi OOlashyn, 
Thanks for developing this, would you mind suggest how I can use it?  I created a single line of text and add the control to that field.
it shows the pdf image not preview, what have I missed?

![image](https://user-images.githubusercontent.com/49010092/87552765-afa6aa80-c6e4-11ea-972a-1a35705c449d.png)

**Comment by OOlashyn** [comment]
Hi @stella12131213 ,
In the small preview window I am not showing a preview of the pdf itself. Rather I am showing a placeholder image (that you can see). To view the pdf itself you need to press on the placeholder image to open full-screen view which has a pdf viewer.
