### ISSUE TITLE
Cannot Import Solution

### ISSUE THREAD

**Issue by onelove2283** [OOlashyn/PCF-AttachmentGalleryControl#9]
Cannot import 
![Solution Error](https://user-images.githubusercontent.com/58792303/90667218-18b59c80-e214-11ea-964e-8d9cb69c1fdd.jpg)

**Comment by OOlashyn** [comment]
Hi @onelove2283,

I just tried to install solution on the trial environment and everything worked just fine. Make sure that you are importing AttachmentGalleryControlSolution_1_0_0_0_managed.zip file from [Release ](https://github.com/OOlashyn/PCF-AttachmentGalleryControl/releases) page (see below).
![image](https://user-images.githubusercontent.com/17760686/90675215-7240ba00-e25a-11ea-8cdb-9e0c4f833318.png)

**Comment by onelove2283** [comment]
I got it work, thank you

Sent from my Sprint Samsung Galaxy A71 5G.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
